config/routes.rb
require 'resque/server'

Rails.application.routes.draw do

  mount Resque::Server.new, at: "/resque"
  
  namespace :api do

    namespace :v1 do
      get 'home', to: 'posts#home'
      post 'posts/create', to: 'posts#create'
      post 'users/sign_in', to: 'users#sign_in'
    end

    namespace :v2 do
       get 'home', to: 'posts#home'

    end

    
  end

  
  # resources :products do
  #   post :get_barcode, on: :collection
  # end




  get 'users/profile/:id', to: 'users#profile'
  get 'users/search', to: 'users#search'
 

  post 'users/upload_avatar/:id', to: 'users#upload_avatar', as: :user_avatar_upload
  

  post 'likes/toggle/:post_id', to: 'likes#toggle', as: :toggle_like

  post 'comments/create', as: :comments
  delete 'comments/:id', to: 'comments#destroy', as: :destroy_comment

	# Post routes
  root 'posts#home'
  get 'posts/home', to: 'posts#home'
  post 'posts/create', as: :posts
  delete 'posts/:id', to: 'posts#destroy', as: :destroy_post

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'visitors/index', to: 'visitors#index'

# rake routes
#               Prefix Verb   URI Pattern                     Controller#Action
# get_barcode_products POST   /products/get_barcode(.:format) products#get_barcode
#             products GET    /products(.:format)             products#index
#                      POST   /products(.:format)             products#create
#          new_product GET    /products/new(.:format)         products#new
#         edit_product GET    /products/:id/edit(.:format)    products#edit
#              product GET    /products/:id(.:format)         products#show
#                      PATCH  /products/:id(.:format)         products#update
#                      PUT    /products/:id(.:format)         products#update
#                      DELETE /products/:id(.:format)         products#destroy
#                 root GET    /                               visitors#index

end

app/models/comment.rb
class Comment < ApplicationRecord

	belongs_to :user
	belongs_to :post
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :destroy]
  before_action :set_comment, only: [:destroy]
  before_action :authorize_user, only: [:destroy]


  def create
  	@new_comment = Comment.create(
  		content: params[:comment][:content], 
  		user_id: current_user.id, 
  		post_id: params[:comment][:post_id]
  		)

    # UserMailer.new_comment(@new_comment.id).deliver_now
    # NewCommentEmailWorker.perform(@new_comment.id)

    Resque.enqueue(NewCommentEmailWorker, @new_comment.id)

    # redirect_to root_path

  end

  def destroy
  	@comment.destroy

  	redirect_to root_path
  end

  private

  def set_comment
  	@comment = Comment.find(params[:id])
  end

  def authorize_user
  	if (@comment.user_id != current_user.id)
  		redirect_to root_path
  	end

  end



end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<li>
	<p><%= comment.content %></p>
		<sub><%= comment.user.email %></sub>
	
	<% if user_signed_in? && comment.user_id ==  current_user.id %>
		<p><span id="cmt-delete-btn"><%= link_to "Delete", destroy_comment_path(comment.id), method: :delete %></span></p>
		<% end %>

</li>

app/views/comments/_post_comment.html.erb
<div class="comments">
	
	<% if user_signed_in? %>
	<%= form_for @comment, remote: true do |f| %>
		<%= f.hidden_field :post_id, value: post.id %>

		
		<%= f.text_area :content,placeholder: "Write something here.." %>
		<%= f.submit %>
	<% end %>
	<% end %>
<div class="comments-list">
	<ul id="post-comment-list-<%= post.id %>">
		<% post.comments.reverse.each do |c| %>
		<%= render 'comments/comment', comment: c %>
		<% end %>
	</ul>

</div>

</div>

app/views/comments/create.js.erb
console.log('creating comment for a post');

var commentsListContainer = $('#post-comment-list-<%= @new_comment.post_id %>')

var newCommentHTML = $("<%= escape_javascript render 'comments/comment', comment: @new_comment %>");

commentsListContainer.prepend(newCommentHTML);

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>